### ISSUE TITLE
Specifying `region` results in incorrect URL

### ISSUE THREAD

**Issue by webdevotion** [bitrise-io/steps-amazon-s3-deploy#15]
`Bitrise.yml` on bitrise.io ( not cli ) spits out:
```
- amazon-s3-deploy@3.4.0:
        inputs:
        - aws_access_key: xxx
        - aws_secret_key: xxx
        - bucket_name: my-bucket-name
        - bucket_region: eu-central-1
        - path_in_bucket: bitrise_{app_slug}/{timestamp}_build_{build_slug}
```

As you can see from the logs the `url` is incorrect and is missing any reference to the Amazon servers:
```
load failed: ../deploy/app.ipa to 
s3://my-bucket-name/bitrise_{app_slug}/{timestamp}_build_{build_slug}/app.ipa
```

Some more details in the error log about regions from the `AWS SDK`:
```
A client error (InvalidRequest) occurred when calling the CreateMultipartUpload operation: 
You are attempting to operate on a bucket in a region that requires Signature Version 4.  
You can fix this issue by explicitly providing the correct region location using the --region argument, 
the AWS_DEFAULT_REGION environment variable, 
or the region variable in the AWS CLI configuration file.  
You can get the bucket's location by running "aws s3api get-bucket-location --bucket BUCKET".
```
